# IMPORTS

In [1]:
import pandas as pd
import numpy as np
import os

pd.set_option("display.max_columns", None)

# File paths

In [2]:
election_path = "../data/raw/countypres_2000-2024.csv"
model_ready_path = "../data/processed/model_ready_dataset.csv"

output_path = "../data/processed/historical_model_ready_dataset.csv"

# Load datasets

In [3]:
election_df = pd.read_csv(election_path)

model_df = pd.read_csv(
    model_ready_path,
    dtype={"county_fips": str},
    low_memory=False
)

model_df["county_fips"] = model_df["county_fips"].astype(str).str.zfill(5)

print("Election dataset shape:", election_df.shape)
print("Model-ready dataset shape:", model_df.shape)

display(election_df.head())
display(model_df.head())

Election dataset shape: (94151, 12)
Model-ready dataset shape: (3115, 182)

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,ALABAMA,AUTAUGA,2024,AL,1001.0,US PRESIDENT,OTHER,OTHER,293.0,28281,20260225,TOTAL
1,ALABAMA,AUTAUGA,2024,AL,1001.0,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,65.0,28281,20260225,TOTAL
2,ALABAMA,AUTAUGA,2024,AL,1001.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,7439.0,28281,20260225,TOTAL
3,ALABAMA,AUTAUGA,2024,AL,1001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,20484.0,28281,20260225,TOTAL
4,ALABAMA,BALDWIN,2024,AL,1003.0,US PRESIDENT,OTHER,OTHER,1276.0,122249,20260225,TOTAL

,GEO_ID,NAME,county_fips,B01001_001E,B01001_002E,B01001_003E,B01001_004E,B01001_005E,B01001_006E,B01001_007E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B01001_014E,B01001_015E,B01001_016E,B01001_017E,B01001_018E,B01001_019E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E,B01001_026E,B01001_027E,B01001_028E,B01001_029E,B01001_030E,B01001_031E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_038E,B01001_039E,B01001_040E,B01001_041E,B01001_042E,B01001_043E,B01001_044E,B01001_045E,B01001_046E,B01001_047E,B01001_048E,B01001_049E,B02001_001E,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_007E,B02001_008E,B02001_009E,B02001_010E,B15003_001E,B15003_002E,B15003_003E,B15003_004E,B15003_005E,B15003_006E,B15003_007E,B15003_008E,B15003_009E,B15003_010E,B15003_011E,B15003_012E,B15003_013E,B15003_014E,B15003_015E,B15003_016E,B15003_017E,B15003_018E,B15003_019E,B15003_020E,B15003_021E,B15003_022E,B15003_023E,B15003_024E,B15003_025E,B19013_001E,B17001_001E,B17001_002E,B17001_003E,B17001_004E,B17001_005E,B17001_006E,B17001_007E,B17001_008E,B17001_009E,B17001_010E,B17001_011E,B17001_012E,B17001_013E,B17001_014E,B17001_015E,B17001_016E,B17001_017E,B17001_018E,B17001_019E,B17001_020E,B17001_021E,B17001_022E,B17001_023E,B17001_024E,B17001_025E,B17001_026E,B17001_027E,B17001_028E,B17001_029E,B17001_030E,B17001_031E,B17001_032E,B17001_033E,B17001_034E,B17001_035E,B17001_036E,B17001_037E,B17001_038E,B17001_039E,B17001_040E,B17001_041E,B17001_042E,B17001_043E,B17001_044E,B17001_045E,B17001_046E,B17001_047E,B17001_048E,B17001_049E,B17001_050E,B17001_051E,B17001_052E,B17001_053E,B17001_054E,B17001_055E,B17001_056E,B17001_057E,B17001_058E,B17001_059E,B23025_001E,B23025_002E,B23025_003E,B23025_004E,B23025_005E,B23025_006E,B23025_007E,B25001_001E,state,county_name,totalvotes,democrat_votes,republican_votes,party_winner,dem_vote_share,total_population,median_income,total_housing_units,labor_force,unemployed,below_poverty,bachelors_degree,masters_degree,professional_degree,doctorate_degree,white_population,black_population,asian_population,higher_education_rate,poverty_rate,unemployment_rate,white_pct,black_pct,asian_pct,log_population
0,0500000US01001,"Autauga County, Alabama",01001,55639,27052,1727,2156,1674,1208,553,395,225,1127,1789,1669,2043,1394,2015,1937,2025,628,804,429,699,1077,764,389,325,28587,1508,1569,1971,1330,625,224,306,1181,1870,1750,1850,2017,1990,1874,2080,835,800,496,836,1414,1066,358,637,55639,42150,10866,155,649,24,374,1421,346,1075,37860,275,0,0,35,0,17,25,3,124,117,313,718,1250,728,668,9663,2217,2194,5469,3323,6320,3399,504,498,57982.0,55181,8394,3417,257,55,362,244,104,226,357,340,407,479,413,142,31,4977,423,102,770,245,23,214,322,736,676,337,695,281,153,46787,23364,1454,424,2117,594,181,697,1934,3025,2997,3439,3009,2057,1436,23423,1073,152,1318,934,366,727,2014,2884,3174,3507,3005,2460,1809,44360,26025,25316,24580,736,709,18335,23697,ALABAMA,AUTAUGA,27770,7503.0,19838.0,0,0.270184,55639,57982.0,23697,26025,736,8394,6320,3399,504,498,42150,10866,649,0.192689,0.150865,0.028280,0.757562,0.195295,0.011664,10.926658
1,0500000US01003,"Baldwin County, Alabama",01003,218289,105889,6082,5197,8289,4305,2406,1177,792,3581,6064,5977,6787,5979,6763,7037,7434,2273,5145,2762,3855,6007,4273,2163,1541,112400,5878,6362,6882,3998,2296,1245,1123,3113,6220,6126,7022,6623,7374,7396,7802,3702,5123,3058,4236,7008,4669,2556,2588,218289,186504,19153,1514,2033,10,3398,5677,1519,4158,155563,1451,0,63,0,123,70,198,78,638,275,938,1976,3127,2483,3403,34521,7751,10511,23964,14357,31444,13331,2845,2016,61756.0,215170,19739,7803,563,176,462,420,166,267,971,887,664,970,1256,657,344,11936,636,129,821,516,95,378,1111,1678,1060,923,2268,1192,1129,195431,96029,5451,878,6694,4797,1444,2401,6701,10733,11657,12655,13435,11820,7363,99402,5188,983,6370,4117,1030,2460,6446,10668,12563,13834,14316,13017,8410,176852,103116,102795,98768,4027,321,73736,116747,ALABAMA,BALDWIN,109679,24578.0,83544.0,0,0.224090,218289,61756.0,116747,103116,4027,19739,31444,13331,2845,2016,186504,19153,2033,0.227387,0.090426,0.039053,0.854390,0.087741,0.009313,12.293580
2,0500000US01005,"Barbour County, Alabama",01005,25026,13156,660,741,721,467,261,365,103,432,1150,1084,928,856,872,839,809,215,580,301,327,674,429,200,142,11870,672,809,708,444,214,138,54,440,696,713,694,569,659,755,782,360,459,222,566,766,474,335,341,25026,11587,11929,88,122,1,777,522,232,290,17797,384,0,0,0,82,124,7,24,69,233,464,621,971,1029,489,5171,1190,1018,2469,1385,1296,540,118,113,34990.0,22070,6312,2509,440,94,272,199,143,37,440,205,142,142,187,104,104,3803,318,49,564,155,47,78,323,546,536,247,357,275,308,15758,7837,220,9,574,298,75,212,536,1229,821,1068,1089,1083,623,7921,341,80,391,261,43,276,518,863,727,1155,1221,1279,766,20407,9356,9356,8707,649,0,11051,12057,ALABAMA,BARBOUR,10518,4816.0,5622.0,0,0.457882,25026,34990.0,12057,9356,649,6312,1296,540,118,113,11587,11929,122,0.082594,0.252218,0.069367,0.462998,0.476664,0.004875,10.127711
3,0500000US01007,"Bibb County, Alabama",01007,22374,12022,626,693,621,569,323,111,71,524,1023,1011,643,989,841,896,857,304,303,212,457,388,352,104,104,10352,627,493,577,378,193,134,126,321,744,470,922,531,771,627,649,286,444,71,461,580,451,272,224,22374,17138,5045,12,56,0,9,114,0,114,15987,323,0,18,0,0,13,0,34,143,119,328,287,667,756,368,5879,1327,768,2056,1087,1183,481,109,41,51721.0,20748,3755,1865,188,43,234,86,136,111,225,262,174,101,261,24,20,1890,29,0,232,86,50,94,180,162,390,199,276,141,51,16993,8642,438,38,644,236,70,240,691,1299,1059,1375,1044,968,540,8351,598,40,478,234,54,180,594,1044,1063,1194,1095,957,820,18421,8970,8970,8303,667,0,9451,9237,ALABAMA,BIBB,9595,1986.0,7525.0,0,0.206983,22374,51721.0,9237,8970,667,3755,1183,481,109,41,17138,5045,56,0.081076,0.167829,0.074359,0.765978,0.225485,0.002503,10.015700
4,0500000US01009,"Blount County, Alabama",01009,57755,28677,1844,1738,2034,1257,743,378,312,1023,1801,1612,1625,1896,1936,1858,2168,715,1102,476,1073,1297,630,752,407,29078,1661,1748,2043,1047,628,325,203,957,1782,1684,1519,2020,1992,1844,1767,893,1218,708,1050,1415,868,856,850,57755,54271,808,55,236,55,1037,1293,264,1029,39814,805,14,0,5,19,50,343,94,781,341,498,723,1338,1048,779,10582,3393,3415,5090,5220,3540,1382,222,132,48922.0,57127,7847,3278,278,72,423,117,45,137,220,311,242,620,372,265,176,4569,453,58,292,253,55,192,320,511,526,576,322,469,542,49280,24983,1440,266,1937,902,237,838,2236,3057,3227,3132,3608,2514,1589,24297,1206,327,1880,973,267,533,1793,2949,2989,3255,3543,2668,1914,46083,24133,24089,22836,1253,44,21950,24404,ALABAMA,BLOUNT,27588,2640.0,24711.0,0,0.095694,57755,48922.0,24404,24133,1253,7847,3540,1382,222,132,54271,808,236,0.091351,0.135867,0.051921,0.939676,0.013990,0.004086,10.963983

# Check available election years

In [4]:
print("Available election years:")
print(sorted(election_df["year"].dropna().unique()))

Available election years:
[np.int64(2000), np.int64(2004), np.int64(2008), np.int64(2012), np.int64(2016), np.int64(2020), np.int64(2024)]

# Clean election FIPS and filter parties/years

In [5]:
valid_years = [2000, 2004, 2008, 2012, 2016, 2020, 2024]

election_clean = election_df[
    election_df["year"].isin(valid_years)
].copy()

election_clean = election_clean[
    election_clean["party"].isin(["DEMOCRAT", "REPUBLICAN"])
].copy()

election_clean["county_fips"] = pd.to_numeric(
    election_clean["county_fips"],
    errors="coerce"
)

election_clean = election_clean[
    election_clean["county_fips"].notna()
].copy()

election_clean["county_fips"] = (
    election_clean["county_fips"]
    .astype(int)
    .astype(str)
    .str.zfill(5)
)

print(election_clean.shape)
display(election_clean.head())

(52152, 12)

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
2,ALABAMA,AUTAUGA,2024,AL,01001,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,7439.0,28281,20260225,TOTAL
3,ALABAMA,AUTAUGA,2024,AL,01001,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,20484.0,28281,20260225,TOTAL
5,ALABAMA,BALDWIN,2024,AL,01003,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,95798.0,122249,20260225,TOTAL
6,ALABAMA,BALDWIN,2024,AL,01003,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,24934.0,122249,20260225,TOTAL
8,ALABAMA,BARBOUR,2024,AL,01005,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,5606.0,9855,20260225,TOTAL

# Pivot election data to county-year level

In [6]:
election_pivot = election_clean.pivot_table(
    index=["county_fips", "year", "state", "county_name", "totalvotes"],
    columns="party",
    values="candidatevotes",
    aggfunc="sum"
).reset_index()

election_pivot.columns.name = None

election_pivot = election_pivot.rename(columns={
    "DEMOCRAT": "democrat_votes",
    "REPUBLICAN": "republican_votes"
})

election_pivot["democrat_votes"] = election_pivot["democrat_votes"].fillna(0)
election_pivot["republican_votes"] = election_pivot["republican_votes"].fillna(0)

election_pivot["dem_vote_share"] = (
    election_pivot["democrat_votes"] / election_pivot["totalvotes"]
)

election_pivot["party_winner"] = np.where(
    election_pivot["democrat_votes"] > election_pivot["republican_votes"],
    1,
    0
)

print(election_pivot.shape)
display(election_pivot.head())

(22082, 9)

,county_fips,year,state,county_name,totalvotes,democrat_votes,republican_votes,dem_vote_share,party_winner
0,01001,2000,ALABAMA,AUTAUGA,17208,4942.0,11993.0,0.287192,0
1,01001,2004,ALABAMA,AUTAUGA,20081,4758.0,15196.0,0.236940,0
2,01001,2008,ALABAMA,AUTAUGA,23641,6093.0,17403.0,0.257730,0
3,01001,2012,ALABAMA,AUTAUGA,23932,6363.0,17379.0,0.265878,0
4,01001,2016,ALABAMA,AUTAUGA,24973,5936.0,18172.0,0.237697,0

# Check county/year coverage

In [7]:
coverage = election_pivot.groupby("year")["county_fips"].nunique()

print("County count per year:")
display(coverage)

County count per year:

year
2000    3154
2004    3155
2008    3155
2012    3155
2016    3155
2020    3154
2024    3154
Name: county_fips, dtype: int64

# Create wide historical vote-share table

In [8]:
dem_share_wide = election_pivot.pivot_table(
    index="county_fips",
    columns="year",
    values="dem_vote_share",
    aggfunc="first"
)

dem_share_wide.columns = [
    f"dem_share_{int(col)}" for col in dem_share_wide.columns
]

dem_share_wide = dem_share_wide.reset_index()

print(dem_share_wide.shape)
display(dem_share_wide.head())

(3157, 8)

,county_fips,dem_share_2000,dem_share_2004,dem_share_2008,dem_share_2012,dem_share_2016,dem_share_2020,dem_share_2024
0,01001,0.287192,0.236940,0.257730,0.265878,0.237697,0.270184,0.263039
1,01003,0.247822,0.225029,0.238119,0.215894,0.193856,0.224090,0.203961
2,01005,0.499086,0.448362,0.489854,0.513685,0.465278,0.457882,0.421918
3,01007,0.381636,0.274868,0.265965,0.261520,0.212496,0.206983,0.174895
4,01009,0.276915,0.183129,0.145135,0.123719,0.084258,0.095694,0.091468

# Create wide party-winner table

In [9]:
winner_wide = election_pivot.pivot_table(
    index="county_fips",
    columns="year",
    values="party_winner",
    aggfunc="first"
)

winner_wide.columns = [
    f"winner_{int(col)}" for col in winner_wide.columns
]

winner_wide = winner_wide.reset_index()

print(winner_wide.shape)
display(winner_wide.head())

(3157, 8)

,county_fips,winner_2000,winner_2004,winner_2008,winner_2012,winner_2016,winner_2020,winner_2024
0,01001,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,01003,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,01005,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,01007,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,01009,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Merge historical election tables

In [10]:
historical_features = dem_share_wide.merge(
    winner_wide,
    on="county_fips",
    how="inner"
)

print(historical_features.shape)
display(historical_features.head())

(3157, 15)

,county_fips,dem_share_2000,dem_share_2004,dem_share_2008,dem_share_2012,dem_share_2016,dem_share_2020,dem_share_2024,winner_2000,winner_2004,winner_2008,winner_2012,winner_2016,winner_2020,winner_2024
0,01001,0.287192,0.236940,0.257730,0.265878,0.237697,0.270184,0.263039,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,01003,0.247822,0.225029,0.238119,0.215894,0.193856,0.224090,0.203961,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,01005,0.499086,0.448362,0.489854,0.513685,0.465278,0.457882,0.421918,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,01007,0.381636,0.274868,0.265965,0.261520,0.212496,0.206983,0.174895,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,01009,0.276915,0.183129,0.145135,0.123719,0.084258,0.095694,0.091468,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Create historical features from 2000–2020 only

In [11]:
train_years = [2000, 2004, 2008, 2012, 2016, 2020]

dem_share_cols = [f"dem_share_{year}" for year in train_years]
winner_cols = [f"winner_{year}" for year in train_years]

historical_features["avg_dem_share_2000_2020"] = historical_features[dem_share_cols].mean(axis=1)

historical_features["dem_wins_count_2000_2020"] = historical_features[winner_cols].sum(axis=1)

historical_features["vote_volatility_2000_2020"] = historical_features[dem_share_cols].std(axis=1)

historical_features["swing_2016_2020"] = (
    historical_features["dem_share_2020"] -
    historical_features["dem_share_2016"]
)

historical_features["swing_2012_2020"] = (
    historical_features["dem_share_2020"] -
    historical_features["dem_share_2012"]
)

historical_features["swing_2000_2020"] = (
    historical_features["dem_share_2020"] -
    historical_features["dem_share_2000"]
)

# Create 2024 target variables

In [12]:
historical_features["target_2024_party_winner"] = historical_features["winner_2024"]

historical_features["target_2024_dem_vote_share"] = historical_features["dem_share_2024"]

display(
    historical_features[
        [
            "county_fips",
            "avg_dem_share_2000_2020",
            "dem_wins_count_2000_2020",
            "vote_volatility_2000_2020",
            "swing_2016_2020",
            "target_2024_party_winner",
            "target_2024_dem_vote_share"
        ]
    ].head()
)

,county_fips,avg_dem_share_2000_2020,dem_wins_count_2000_2020,vote_volatility_2000_2020,swing_2016_2020,target_2024_party_winner,target_2024_dem_vote_share
0,01001,0.259270,0.0,0.019539,0.032487,0.0,0.263039
1,01003,0.224135,0.0,0.018666,0.030234,0.0,0.203961
2,01005,0.479025,2.0,0.025680,-0.007397,0.0,0.421918
3,01007,0.267245,0.0,0.062940,-0.005513,0.0,0.174895
4,01009,0.151475,0.0,0.070961,0.011436,0.0,0.091468

# Check missing values in historical features

In [13]:
historical_missing = historical_features.isnull().sum()
historical_missing = historical_missing[historical_missing > 0].sort_values(ascending=False)

print("Missing values in historical features:")
display(historical_missing)

Missing values in historical features:

swing_2000_2020               7
swing_2012_2020               5
dem_share_2000                5
dem_share_2004                3
dem_share_2008                3
dem_share_2016                3
dem_share_2012                3
dem_share_2020                3
dem_share_2024                3
swing_2016_2020               3
winner_2024                   3
winner_2000                   3
winner_2020                   3
target_2024_party_winner      3
target_2024_dem_vote_share    3
winner_2008                   2
winner_2004                   2
winner_2016                   2
winner_2012                   2
vote_volatility_2000_2020     1
avg_dem_share_2000_2020       1
dtype: int64

# Remove incomplete historical rows

In [14]:
historical_features = historical_features.dropna().copy()

print("Historical features shape after dropping missing rows:")
print(historical_features.shape)

Historical features shape after dropping missing rows:
(3150, 23)

# Select final historical columns to merge

In [15]:
historical_cols_to_keep = [
    "county_fips",
    
    "dem_share_2000",
    "dem_share_2004",
    "dem_share_2008",
    "dem_share_2012",
    "dem_share_2016",
    "dem_share_2020",
    
    "winner_2000",
    "winner_2004",
    "winner_2008",
    "winner_2012",
    "winner_2016",
    "winner_2020",
    
    "avg_dem_share_2000_2020",
    "dem_wins_count_2000_2020",
    "vote_volatility_2000_2020",
    "swing_2016_2020",
    "swing_2012_2020",
    "swing_2000_2020",
    
    "target_2024_party_winner",
    "target_2024_dem_vote_share"
]

historical_final = historical_features[historical_cols_to_keep].copy()

print(historical_final.shape)
display(historical_final.head())

(3150, 21)

,county_fips,dem_share_2000,dem_share_2004,dem_share_2008,dem_share_2012,dem_share_2016,dem_share_2020,winner_2000,winner_2004,winner_2008,winner_2012,winner_2016,winner_2020,avg_dem_share_2000_2020,dem_wins_count_2000_2020,vote_volatility_2000_2020,swing_2016_2020,swing_2012_2020,swing_2000_2020,target_2024_party_winner,target_2024_dem_vote_share
0,01001,0.287192,0.236940,0.257730,0.265878,0.237697,0.270184,0.0,0.0,0.0,0.0,0.0,0.0,0.259270,0.0,0.019539,0.032487,0.004305,-0.017008,0.0,0.263039
1,01003,0.247822,0.225029,0.238119,0.215894,0.193856,0.224090,0.0,0.0,0.0,0.0,0.0,0.0,0.224135,0.0,0.018666,0.030234,0.008196,-0.023732,0.0,0.203961
2,01005,0.499086,0.448362,0.489854,0.513685,0.465278,0.457882,1.0,0.0,0.0,1.0,0.0,0.0,0.479025,2.0,0.025680,-0.007397,-0.055803,-0.041204,0.0,0.421918
3,01007,0.381636,0.274868,0.265965,0.261520,0.212496,0.206983,0.0,0.0,0.0,0.0,0.0,0.0,0.267245,0.0,0.062940,-0.005513,-0.054537,-0.174654,0.0,0.174895
4,01009,0.276915,0.183129,0.145135,0.123719,0.084258,0.095694,0.0,0.0,0.0,0.0,0.0,0.0,0.151475,0.0,0.070961,0.011436,-0.028025,-0.181222,0.0,0.091468

# Merge historical features with model-ready ACS dataset

In [16]:
final_historical_df = model_df.merge(
    historical_final,
    on="county_fips",
    how="inner"
)

print("Final historical ML dataset shape:")
print(final_historical_df.shape)

display(final_historical_df.head())

Final historical ML dataset shape:
(3113, 202)

,GEO_ID,NAME,county_fips,B01001_001E,B01001_002E,B01001_003E,B01001_004E,B01001_005E,B01001_006E,B01001_007E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B01001_014E,B01001_015E,B01001_016E,B01001_017E,B01001_018E,B01001_019E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E,B01001_026E,B01001_027E,B01001_028E,B01001_029E,B01001_030E,B01001_031E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_038E,B01001_039E,B01001_040E,B01001_041E,B01001_042E,B01001_043E,B01001_044E,B01001_045E,B01001_046E,B01001_047E,B01001_048E,B01001_049E,B02001_001E,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_007E,B02001_008E,B02001_009E,B02001_010E,B15003_001E,B15003_002E,B15003_003E,B15003_004E,B15003_005E,B15003_006E,B15003_007E,B15003_008E,B15003_009E,B15003_010E,B15003_011E,B15003_012E,B15003_013E,B15003_014E,B15003_015E,B15003_016E,B15003_017E,B15003_018E,B15003_019E,B15003_020E,B15003_021E,B15003_022E,B15003_023E,B15003_024E,B15003_025E,B19013_001E,B17001_001E,B17001_002E,B17001_003E,B17001_004E,B17001_005E,B17001_006E,B17001_007E,B17001_008E,B17001_009E,B17001_010E,B17001_011E,B17001_012E,B17001_013E,B17001_014E,B17001_015E,B17001_016E,B17001_017E,B17001_018E,B17001_019E,B17001_020E,B17001_021E,B17001_022E,B17001_023E,B17001_024E,B17001_025E,B17001_026E,B17001_027E,B17001_028E,B17001_029E,B17001_030E,B17001_031E,B17001_032E,B17001_033E,B17001_034E,B17001_035E,B17001_036E,B17001_037E,B17001_038E,B17001_039E,B17001_040E,B17001_041E,B17001_042E,B17001_043E,B17001_044E,B17001_045E,B17001_046E,B17001_047E,B17001_048E,B17001_049E,B17001_050E,B17001_051E,B17001_052E,B17001_053E,B17001_054E,B17001_055E,B17001_056E,B17001_057E,B17001_058E,B17001_059E,B23025_001E,B23025_002E,B23025_003E,B23025_004E,B23025_005E,B23025_006E,B23025_007E,B25001_001E,state,county_name,totalvotes,democrat_votes,republican_votes,party_winner,dem_vote_share,total_population,median_income,total_housing_units,labor_force,unemployed,below_poverty,bachelors_degree,masters_degree,professional_degree,doctorate_degree,white_population,black_population,asian_population,higher_education_rate,poverty_rate,unemployment_rate,white_pct,black_pct,asian_pct,log_population,dem_share_2000,dem_share_2004,dem_share_2008,dem_share_2012,dem_share_2016,dem_share_2020,winner_2000,winner_2004,winner_2008,winner_2012,winner_2016,winner_2020,avg_dem_share_2000_2020,dem_wins_count_2000_2020,vote_volatility_2000_2020,swing_2016_2020,swing_2012_2020,swing_2000_2020,target_2024_party_winner,target_2024_dem_vote_share
0,0500000US01001,"Autauga County, Alabama",01001,55639,27052,1727,2156,1674,1208,553,395,225,1127,1789,1669,2043,1394,2015,1937,2025,628,804,429,699,1077,764,389,325,28587,1508,1569,1971,1330,625,224,306,1181,1870,1750,1850,2017,1990,1874,2080,835,800,496,836,1414,1066,358,637,55639,42150,10866,155,649,24,374,1421,346,1075,37860,275,0,0,35,0,17,25,3,124,117,313,718,1250,728,668,9663,2217,2194,5469,3323,6320,3399,504,498,57982.0,55181,8394,3417,257,55,362,244,104,226,357,340,407,479,413,142,31,4977,423,102,770,245,23,214,322,736,676,337,695,281,153,46787,23364,1454,424,2117,594,181,697,1934,3025,2997,3439,3009,2057,1436,23423,1073,152,1318,934,366,727,2014,2884,3174,3507,3005,2460,1809,44360,26025,25316,24580,736,709,18335,23697,ALABAMA,AUTAUGA,27770,7503.0,19838.0,0,0.270184,55639,57982.0,23697,26025,736,8394,6320,3399,504,498,42150,10866,649,0.192689,0.150865,0.028280,0.757562,0.195295,0.011664,10.926658,0.287192,0.236940,0.257730,0.265878,0.237697,0.270184,0.0,0.0,0.0,0.0,0.0,0.0,0.259270,0.0,0.019539,0.032487,0.004305,-0.017008,0.0,0.263039
1,0500000US01003,"Baldwin County, Alabama",01003,218289,105889,6082,5197,8289,4305,2406,1177,792,3581,6064,5977,6787,5979,6763,7037,7434,2273,5145,2762,3855,6007,4273,2163,1541,112400,5878,6362,6882,3998,2296,1245,1123,3113,6220,6126,7022,6623,7374,7396,7802,3702,5123,3058,4236,7008,4669,2556,2588,218289,186504,19153,1514,2033,10,3398,5677,1519,4158,155563,1451,0,63,0,123,70,198,78,638,275,938,1976,3127,2483,3403,34521,7751,10511,23964,14357,31444,13331,2845,2016,61756.0,215170,19739,7803,563,176,462,420,166,267,971,887,664,970,1256,657,344,11936,636,129,821,516,95,378,1111,1678,1060,923,2268,1192,1129,195431,96029,5451,878,6694,4797,1444,2401,6701,10733,11657,12655,13435,11820,7363,99402,5188,983,6370,4117,1030,2460,6446,10668,12563,13834,14316,13017,8410,176852,103116,102795,98768,4027,321,73736,116747,ALABAMA,BALDWIN,109679,24578.0,83544.0,0,0.224090,218289,61756.0,116747,103116,4027,19739,31444,13331,2845,2016,186504,19153,2033,0.227387,0.090426,0.039053,0.854390,0.087741,0.009313,12.293580,0.247822,0.225029,0.238119,0.215894,0.193856,0.224090,0.0,0.0,0.0,0.0,0.0,0.0,0.224135,0.0,0.018666,0.030234,0.008196,-0.023732,0.0,0.203961
2,0500000US01005,"Barbour County, Alabama",01005,25026,13156,660,741,721,467,261,365,103,432,1150,1084,928,856,872,839,809,215,580,301,327,674,429,200,142,11870,672,809,708,444,214,138,54,440,696,713,694,569,659,755,782,360,459,222,566,766,474,335,341,25026,11587,11929,88,122,1,777,522,232,290,17797,384,0,0,0,82,124,7,24,69,233,464,621,971,1029,489,5171,1190,1018,2469,1385,1296,540,118,113,34990.0,22070,6312,2509,440,94,272,199,143,37,440,205,142,142,187,104,104,3803,318,49,564,155,47,78,323,546,536,247,357,275,308,15758,7837,220,9,574,298,75,212,536,1229,821,1068,1089,1083,623,7921,341,80,391,261,43,276,518,863,727,1155,1221,1279,766,20407,9356,9356,8707,649,0,11051,12057,ALABAMA,BARBOUR,10518,4816.0,5622.0,0,0.457882,25026,34990.0,12057,9356,649,6312,1296,540,118,113,11587,11929,122,0.082594,0.252218,0.069367,0.462998,0.476664,0.004875,10.127711,0.499086,0.448362,0.489854,0.513685,0.465278,0.457882,1.0,0.0,0.0,1.0,0.0,0.0,0.479025,2.0,0.025680,-0.007397,-0.055803,-0.041204,0.0,0.421918
3,0500000US01007,"Bibb County, Alabama",01007,22374,12022,626,693,621,569,323,111,71,524,1023,1011,643,989,841,896,857,304,303,212,457,388,352,104,104,10352,627,493,577,378,193,134,126,321,744,470,922,531,771,627,649,286,444,71,461,580,451,272,224,22374,17138,5045,12,56,0,9,114,0,114,15987,323,0,18,0,0,13,0,34,143,119,328,287,667,756,368,5879,1327,768,2056,1087,1183,481,109,41,51721.0,20748,3755,1865,188,43,234,86,136,111,225,262,174,101,261,24,20,1890,29,0,232,86,50,94,180,162,390,199,276,141,51,16993,8642,438,38,644,236,70,240,691,1299,1059,1375,1044,968,540,8351,598,40,478,234,54,180,594,1044,1063,1194,1095,957,820,18421,8970,8970,8303,667,0,9451,9237,ALABAMA,BIBB,9595,1986.0,7525.0,0,0.206983,22374,51721.0,9237,8970,667,3755,1183,481,109,41,17138,5045,56,0.081076,0.167829,0.074359,0.765978,0.225485,0.002503,10.015700,0.381636,0.274868,0.265965,0.261520,0.212496,0.206983,0.0,0.0,0.0,0.0,0.0,0.0,0.267245,0.0,0.062940,-0.005513,-0.054537,-0.174654,0.0,0.174895
4,0500000US01009,"Blount County, Alabama",01009,57755,28677,1844,1738,2034,1257,743,378,312,1023,1801,1612,1625,1896,1936,1858,2168,715,1102,476,1073,1297,630,752,407,29078,1661,1748,2043,1047,628,325,203,957,1782,1684,1519,2020,1992,1844,1767,893,1218,708,1050,1415,868,856,850,57755,54271,808,55,236,55,1037,1293,264,1029,39814,805,14,0,5,19,50,343,94,781,341,498,723,1338,1048,779,10582,3393,3415,5090,5220,3540,1382,222,132,48922.0,57127,7847,3278,278,72,423,117,45,137,220,311,242,620,372,265,176,4569,453,58,292,253,55,192,320,511,526,576,322,469,542,49280,24983,1440,266,1937,902,237,838,2236,3057,3227,3132,3608,2514,1589,24297,1206,327,1880,973,267,533,1793,2949,2989,3255,3543,2668,1914,46083,24133,24089,22836,1253,44,21950,24404,ALABAMA,BLOUNT,27588,2640.0,24711.0,0,0.095694,57755,48922.0,24404,24133,1253,7847,3540,1382,222,132,54271,808,236,0.091351,0.135867,0.051921,0.939676,0.013990,0.004086,10.963983,0.276915,0.183129,0.145135,0.123719,0.084258,0.095694,0.0,0.0,0.0,0.0,0.0,0.0,0.151475,0.0,0.070961,0.011436,-0.028025,-0.181222,0.0,0.091468

# Check target distribution for 2024

In [17]:
print("2024 target class balance:")
print(final_historical_df["target_2024_party_winner"].value_counts())

print("\n2024 target class percentage:")
print(final_historical_df["target_2024_party_winner"].value_counts(normalize=True))

print("\n2024 Democratic vote share summary:")
display(final_historical_df["target_2024_dem_vote_share"].describe())

2024 target class balance:
target_2024_party_winner
0.0    2661
1.0     452
Name: count, dtype: int64

2024 target class percentage:
target_2024_party_winner
0.0    0.854802
1.0    0.145198
Name: proportion, dtype: float64

2024 Democratic vote share summary:

count    3113.000000
mean        0.374041
std         0.208182
min         0.038462
25%         0.219230
50%         0.328390
75%         0.480322
max         1.576209
Name: target_2024_dem_vote_share, dtype: float64

# Check missing values in final dataset

In [18]:
missing_final = final_historical_df.isnull().sum()
missing_final = missing_final[missing_final > 0].sort_values(ascending=False)

print("Missing values in final historical dataset:")
display(missing_final)

Missing values in final historical dataset:

B19013_001E      1
median_income    1
dtype: int64

# Remove Invalid Vote Shares

In [19]:
final_historical_df = final_historical_df[
    final_historical_df["target_2024_dem_vote_share"] <= 1
].copy()

print("Dataset shape after removing invalid vote shares:")
print(final_historical_df.shape)

print("\nUpdated target vote share summary:")
display(
    final_historical_df["target_2024_dem_vote_share"].describe()
)

Dataset shape after removing invalid vote shares:
(3064, 202)

Updated target vote share summary:

count    3064.000000
mean        0.361461
std         0.183583
min         0.038462
25%         0.217894
50%         0.324817
75%         0.471770
max         0.997539
Name: target_2024_dem_vote_share, dtype: float64

# Remove Remaining Missing Values

In [20]:
final_historical_df = final_historical_df.dropna().copy()

print("Final cleaned dataset shape:")
print(final_historical_df.shape)

print("\nRemaining missing values:")
print(final_historical_df.isnull().sum().sum())

Final cleaned dataset shape:
(3063, 202)

Remaining missing values:
0

# Save final historical ML dataset

In [21]:
os.makedirs("../data/processed", exist_ok=True)

final_historical_df.to_csv(output_path, index=False)

print("Historical model-ready dataset saved successfully:")
print(output_path)

Historical model-ready dataset saved successfully:
../data/processed/historical_model_ready_dataset.csv

# Reload and verify

In [22]:
verified_df = pd.read_csv(
    output_path,
    dtype={"county_fips": str},
    low_memory=False
)

verified_df["county_fips"] = verified_df["county_fips"].astype(str).str.zfill(5)

print(verified_df.shape)
display(verified_df.head())

(3063, 202)

,GEO_ID,NAME,county_fips,B01001_001E,B01001_002E,B01001_003E,B01001_004E,B01001_005E,B01001_006E,B01001_007E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B01001_014E,B01001_015E,B01001_016E,B01001_017E,B01001_018E,B01001_019E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E,B01001_026E,B01001_027E,B01001_028E,B01001_029E,B01001_030E,B01001_031E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_038E,B01001_039E,B01001_040E,B01001_041E,B01001_042E,B01001_043E,B01001_044E,B01001_045E,B01001_046E,B01001_047E,B01001_048E,B01001_049E,B02001_001E,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_007E,B02001_008E,B02001_009E,B02001_010E,B15003_001E,B15003_002E,B15003_003E,B15003_004E,B15003_005E,B15003_006E,B15003_007E,B15003_008E,B15003_009E,B15003_010E,B15003_011E,B15003_012E,B15003_013E,B15003_014E,B15003_015E,B15003_016E,B15003_017E,B15003_018E,B15003_019E,B15003_020E,B15003_021E,B15003_022E,B15003_023E,B15003_024E,B15003_025E,B19013_001E,B17001_001E,B17001_002E,B17001_003E,B17001_004E,B17001_005E,B17001_006E,B17001_007E,B17001_008E,B17001_009E,B17001_010E,B17001_011E,B17001_012E,B17001_013E,B17001_014E,B17001_015E,B17001_016E,B17001_017E,B17001_018E,B17001_019E,B17001_020E,B17001_021E,B17001_022E,B17001_023E,B17001_024E,B17001_025E,B17001_026E,B17001_027E,B17001_028E,B17001_029E,B17001_030E,B17001_031E,B17001_032E,B17001_033E,B17001_034E,B17001_035E,B17001_036E,B17001_037E,B17001_038E,B17001_039E,B17001_040E,B17001_041E,B17001_042E,B17001_043E,B17001_044E,B17001_045E,B17001_046E,B17001_047E,B17001_048E,B17001_049E,B17001_050E,B17001_051E,B17001_052E,B17001_053E,B17001_054E,B17001_055E,B17001_056E,B17001_057E,B17001_058E,B17001_059E,B23025_001E,B23025_002E,B23025_003E,B23025_004E,B23025_005E,B23025_006E,B23025_007E,B25001_001E,state,county_name,totalvotes,democrat_votes,republican_votes,party_winner,dem_vote_share,total_population,median_income,total_housing_units,labor_force,unemployed,below_poverty,bachelors_degree,masters_degree,professional_degree,doctorate_degree,white_population,black_population,asian_population,higher_education_rate,poverty_rate,unemployment_rate,white_pct,black_pct,asian_pct,log_population,dem_share_2000,dem_share_2004,dem_share_2008,dem_share_2012,dem_share_2016,dem_share_2020,winner_2000,winner_2004,winner_2008,winner_2012,winner_2016,winner_2020,avg_dem_share_2000_2020,dem_wins_count_2000_2020,vote_volatility_2000_2020,swing_2016_2020,swing_2012_2020,swing_2000_2020,target_2024_party_winner,target_2024_dem_vote_share
0,0500000US01001,"Autauga County, Alabama",01001,55639,27052,1727,2156,1674,1208,553,395,225,1127,1789,1669,2043,1394,2015,1937,2025,628,804,429,699,1077,764,389,325,28587,1508,1569,1971,1330,625,224,306,1181,1870,1750,1850,2017,1990,1874,2080,835,800,496,836,1414,1066,358,637,55639,42150,10866,155,649,24,374,1421,346,1075,37860,275,0,0,35,0,17,25,3,124,117,313,718,1250,728,668,9663,2217,2194,5469,3323,6320,3399,504,498,57982.0,55181,8394,3417,257,55,362,244,104,226,357,340,407,479,413,142,31,4977,423,102,770,245,23,214,322,736,676,337,695,281,153,46787,23364,1454,424,2117,594,181,697,1934,3025,2997,3439,3009,2057,1436,23423,1073,152,1318,934,366,727,2014,2884,3174,3507,3005,2460,1809,44360,26025,25316,24580,736,709,18335,23697,ALABAMA,AUTAUGA,27770,7503.0,19838.0,0,0.270184,55639,57982.0,23697,26025,736,8394,6320,3399,504,498,42150,10866,649,0.192689,0.150865,0.028280,0.757562,0.195295,0.011664,10.926658,0.287192,0.236940,0.257730,0.265878,0.237697,0.270184,0.0,0.0,0.0,0.0,0.0,0.0,0.259270,0.0,0.019539,0.032487,0.004305,-0.017008,0.0,0.263039
1,0500000US01003,"Baldwin County, Alabama",01003,218289,105889,6082,5197,8289,4305,2406,1177,792,3581,6064,5977,6787,5979,6763,7037,7434,2273,5145,2762,3855,6007,4273,2163,1541,112400,5878,6362,6882,3998,2296,1245,1123,3113,6220,6126,7022,6623,7374,7396,7802,3702,5123,3058,4236,7008,4669,2556,2588,218289,186504,19153,1514,2033,10,3398,5677,1519,4158,155563,1451,0,63,0,123,70,198,78,638,275,938,1976,3127,2483,3403,34521,7751,10511,23964,14357,31444,13331,2845,2016,61756.0,215170,19739,7803,563,176,462,420,166,267,971,887,664,970,1256,657,344,11936,636,129,821,516,95,378,1111,1678,1060,923,2268,1192,1129,195431,96029,5451,878,6694,4797,1444,2401,6701,10733,11657,12655,13435,11820,7363,99402,5188,983,6370,4117,1030,2460,6446,10668,12563,13834,14316,13017,8410,176852,103116,102795,98768,4027,321,73736,116747,ALABAMA,BALDWIN,109679,24578.0,83544.0,0,0.224090,218289,61756.0,116747,103116,4027,19739,31444,13331,2845,2016,186504,19153,2033,0.227387,0.090426,0.039053,0.854390,0.087741,0.009313,12.293580,0.247822,0.225029,0.238119,0.215894,0.193856,0.224090,0.0,0.0,0.0,0.0,0.0,0.0,0.224135,0.0,0.018666,0.030234,0.008196,-0.023732,0.0,0.203961
2,0500000US01005,"Barbour County, Alabama",01005,25026,13156,660,741,721,467,261,365,103,432,1150,1084,928,856,872,839,809,215,580,301,327,674,429,200,142,11870,672,809,708,444,214,138,54,440,696,713,694,569,659,755,782,360,459,222,566,766,474,335,341,25026,11587,11929,88,122,1,777,522,232,290,17797,384,0,0,0,82,124,7,24,69,233,464,621,971,1029,489,5171,1190,1018,2469,1385,1296,540,118,113,34990.0,22070,6312,2509,440,94,272,199,143,37,440,205,142,142,187,104,104,3803,318,49,564,155,47,78,323,546,536,247,357,275,308,15758,7837,220,9,574,298,75,212,536,1229,821,1068,1089,1083,623,7921,341,80,391,261,43,276,518,863,727,1155,1221,1279,766,20407,9356,9356,8707,649,0,11051,12057,ALABAMA,BARBOUR,10518,4816.0,5622.0,0,0.457882,25026,34990.0,12057,9356,649,6312,1296,540,118,113,11587,11929,122,0.082594,0.252218,0.069367,0.462998,0.476664,0.004875,10.127711,0.499086,0.448362,0.489854,0.513685,0.465278,0.457882,1.0,0.0,0.0,1.0,0.0,0.0,0.479025,2.0,0.025680,-0.007397,-0.055803,-0.041204,0.0,0.421918
3,0500000US01007,"Bibb County, Alabama",01007,22374,12022,626,693,621,569,323,111,71,524,1023,1011,643,989,841,896,857,304,303,212,457,388,352,104,104,10352,627,493,577,378,193,134,126,321,744,470,922,531,771,627,649,286,444,71,461,580,451,272,224,22374,17138,5045,12,56,0,9,114,0,114,15987,323,0,18,0,0,13,0,34,143,119,328,287,667,756,368,5879,1327,768,2056,1087,1183,481,109,41,51721.0,20748,3755,1865,188,43,234,86,136,111,225,262,174,101,261,24,20,1890,29,0,232,86,50,94,180,162,390,199,276,141,51,16993,8642,438,38,644,236,70,240,691,1299,1059,1375,1044,968,540,8351,598,40,478,234,54,180,594,1044,1063,1194,1095,957,820,18421,8970,8970,8303,667,0,9451,9237,ALABAMA,BIBB,9595,1986.0,7525.0,0,0.206983,22374,51721.0,9237,8970,667,3755,1183,481,109,41,17138,5045,56,0.081076,0.167829,0.074359,0.765978,0.225485,0.002503,10.015700,0.381636,0.274868,0.265965,0.261520,0.212496,0.206983,0.0,0.0,0.0,0.0,0.0,0.0,0.267245,0.0,0.062940,-0.005513,-0.054537,-0.174654,0.0,0.174895
4,0500000US01009,"Blount County, Alabama",01009,57755,28677,1844,1738,2034,1257,743,378,312,1023,1801,1612,1625,1896,1936,1858,2168,715,1102,476,1073,1297,630,752,407,29078,1661,1748,2043,1047,628,325,203,957,1782,1684,1519,2020,1992,1844,1767,893,1218,708,1050,1415,868,856,850,57755,54271,808,55,236,55,1037,1293,264,1029,39814,805,14,0,5,19,50,343,94,781,341,498,723,1338,1048,779,10582,3393,3415,5090,5220,3540,1382,222,132,48922.0,57127,7847,3278,278,72,423,117,45,137,220,311,242,620,372,265,176,4569,453,58,292,253,55,192,320,511,526,576,322,469,542,49280,24983,1440,266,1937,902,237,838,2236,3057,3227,3132,3608,2514,1589,24297,1206,327,1880,973,267,533,1793,2949,2989,3255,3543,2668,1914,46083,24133,24089,22836,1253,44,21950,24404,ALABAMA,BLOUNT,27588,2640.0,24711.0,0,0.095694,57755,48922.0,24404,24133,1253,7847,3540,1382,222,132,54271,808,236,0.091351,0.135867,0.051921,0.939676,0.013990,0.004086,10.963983,0.276915,0.183129,0.145135,0.123719,0.084258,0.095694,0.0,0.0,0.0,0.0,0.0,0.0,0.151475,0.0,0.070961,0.011436,-0.028025,-0.181222,0.0,0.091468